id: P005410
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG25162
  title: ཀློང་རྡོལ་བླ་མའི་རྣམ་ཐར།
  author: ''
  volumes:
    cf64521e6316457cba4c038266898783:
      image_group_id: I1KG25164
      title: ''
      volume_number: 1
      total_pages: 380
      base_file: v001.txt
