id: I17939170
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T02:30:27+00:00'
last_modified: '2022-06-08T02:53:11.387919+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25162
  title: ཀློང་རྡོལ་བླ་མའི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    90C3:
      image_group_id: I1KG25164
      title: ''
      total_pages: 380
      order: 1
      base_file: 90C3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
